# ---------------------------------------
# BUILD STAGE
# ---------------------------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .
RUN dotnet publish -c Release -o /app/publish

# ---------------------------------------
# RUNTIME STAGE
# ---------------------------------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:5281

COPY --from=build /app/publish .

EXPOSE 5281

ENTRYPOINT ["dotnet", "FloresFuertes.dll"]