// app/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./components/Nav";
import "./globals.css";

// 1. IMPORTEER DE AUTH PROVIDER
import { AuthProvider } from "./context/AuthContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* 2. WIKKEL ALLES IN DE PROVIDER */}
        <AuthProvider>
          <Nav /> {/* Je Nav component staat nu BINNEN de provider */}
          <main>
            {children} {/* Je paginas staan nu BINNEN de provider */}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}